'use strict'

const { bumpGt, firstLine } = require('./version.js')

// Stable HTML-comment marker used to locate and overwrite the single bot comment.
const MARKER = '<!-- intent -->'
const GENERATED_HEADER = '### Intent Release Check'
const GENERATED_FOOTER = 'Generated by Intent'

const BUMP_REASON = {
  major: 'breaking change (`!` indicator or `BREAKING CHANGE` footer)',
  minor: '`feat` introduces new functionality',
  patch: '`fix` or `perf` corrects existing behaviour',
  none: 'no releasable change (`chore`, `docs`, `ci`, ...)',
}

// --- Markdown sanitization -------------------------------------------------------------------------------------------
// User-controlled strings (PR title, commit subjects) are always rendered inside an inline-code span.
// That neutralizes @mentions and #refs (no stray notifications) and most Markdown.
// Two characters still need handling:
//   - backtick: would close the code span early
//   - pipe:     breaks table-cell layout (escaped per GFM, only inside cells)

/** Collapses whitespace and removes backticks; never wraps. */
function clean(str) {
  return String(str ?? '')
    .replace(/\s+/g, ' ')
    .replace(/`/g, "'")
    .trim()
}

/** Inline-code span for prose. */
function code(str) {
  return `\`${clean(str)}\``
}

/** Inline-code span for a table cell: also escapes pipes (GFM unescapes them). */
function cell(str, maxLen) {
  let text = clean(str)
  if (maxLen && text.length > maxLen) {
    text = `${text.slice(0, maxLen - 1)}...`
  }
  return `\`${text.replace(/\|/g, '\\|')}\``
}

function shortSha(sha) {
  return String(sha ?? '').slice(0, 7)
}

function buildFooter(now = new Date()) {
  const pad = (n) => String(n).padStart(2, '0')
  const ts = `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())} ${pad(
    now.getUTCHours(),
  )}:${pad(now.getUTCMinutes())} UTC`
  return `_Last updated: ${ts} - ${GENERATED_FOOTER}_`
}

function bumpCell(bumpLevel, isConflict) {
  if (!bumpLevel || bumpLevel === 'none') return '--'
  // bumpLevel is from a fixed enum, safe to interpolate without sanitizing.
  return isConflict ? `**\`${bumpLevel}\`** :warning:` : `\`${bumpLevel}\``
}

function hasBreakingFooter(message) {
  return String(message ?? '')
    .split(/\r?\n/)
    .some((line) => /^BREAKING[ -]CHANGE:/.test(line.trim()))
}

function hasBreakingBang(message) {
  return /^([a-z]+)(\([^)]+\))?!: /.test(firstLine(message))
}

function bumpReason(message, bumpLevel) {
  if (bumpLevel === 'major') {
    const bang = hasBreakingBang(message)
    const footer = hasBreakingFooter(message)
    if (bang && footer) return 'contains `!` and a `BREAKING CHANGE` footer'
    if (bang) return 'contains `!`'
    if (footer) return 'contains a `BREAKING CHANGE` footer'
    return 'marks a breaking change'
  }
  if (bumpLevel === 'minor') return '`feat:` means new functionality'
  if (bumpLevel === 'patch') return '`fix:` or `perf:` means a patch change'
  return '--'
}

function commitsTable(commitAnalysis, titleBump) {
  const rows = commitAnalysis.map(({ sha, message, result }) => {
    const subject = firstLine(message)
    const bump = result.bumpLevel ?? 'none'
    // A commit contributes a bump even when its subject is not valid CC -- e.g. a non-CC subject carrying a
    // BREAKING CHANGE footer. Display and conflict marking therefore key off the bump level, not the validity flag.
    const isConflict = bumpGt(bump, titleBump)
    return `| \`${shortSha(sha)}\` | ${cell(subject, 72)} | ${bumpCell(bump, isConflict)} | ${bumpReason(
      message,
      bump,
    )} |`
  })

  return ['| SHA | Subject | Bump | Reason |', '| :-- | :------ | :--: | :----- |', ...rows].join('\n')
}

function detailsSection(commitAnalysis, titleBump) {
  if (commitAnalysis.length === 0) return ''
  const n = commitAnalysis.length
  return [
    '',
    '<details>',
    `<summary>${n} commit${n === 1 ? '' : 's'} analyzed</summary>`,
    '',
    commitsTable(commitAnalysis, titleBump),
    '',
    '</details>',
  ].join('\n')
}

// --- Comment variants ------------------------------------------------------------------------------------------------

// GitHub Markdown alert. A failing check uses CAUTION (red) so it is hard to miss.
// Content lines are blockquote-prefixed; an empty string becomes a quoted blank line.
function alert(type, contentLines) {
  const body = contentLines.map((line) => (line === '' ? '>' : `> ${line}`))
  return [`> [!${type}]`, ...body].join('\n')
}

function buildInvalidTitleComment(title) {
  return [
    MARKER,
    '',
    GENERATED_HEADER,
    '',
    alert('CAUTION', [
      '**Intent &middot; Invalid PR Title**',
      '',
      'Intent uses the PR title as the release signal, and this title does not follow [Conventional Commits v1.0.0](https://www.conventionalcommits.org/) format.',
      '',
      `**Got:** ${code(title || '(empty)')}`,
      '**Expected:** `<type>[scope][!]: <description>`',
      '',
      '**Allowed types:** `build`, `chore`, `ci`, `docs`, `feat`, `fix`, `perf`, `refactor`, `revert`, `style`, `test`',
      '',
      '**How to fix:** Edit the PR title in GitHub -- for example: `feat: add login` or `fix(auth)!: remove deprecated endpoint`',
    ]),
    '',
    buildFooter(),
  ].join('\n')
}

// Example title prefix that yields each bump level, used in the fix suggestion.
const EXAMPLE_PREFIX = { major: 'feat!', minor: 'feat', patch: 'fix' }

function buildConflictComment(title, titleBump, maxCommitBump, commitAnalysis) {
  const desc = firstLine(title).replace(/^[a-z]+(\([^)]+\))?!?: /i, '') || 'description'
  const prefix = EXAMPLE_PREFIX[maxCommitBump] ?? 'feat'
  const example = code(`${prefix}: ${desc}`)

  return [
    MARKER,
    '',
    GENERATED_HEADER,
    '',
    alert('CAUTION', [
      '**Intent &middot; Release Intent Mismatch**',
      '',
      `The PR title declares a **\`${titleBump}\`** bump: ${code(title)}`,
      '',
      `One or more commits imply a higher **\`${maxCommitBump}\`** bump.`,
      '',
      '**Choose the fix that matches the real intent:**',
      `- If the commit message is correct, update the PR title to declare **\`${maxCommitBump}\`**, e.g. ${example}`,
      '- If a flagged commit message overstates the change, rewrite that commit message so it no longer implies a higher bump.',
      '- If this PR will be squash-merged, make sure the final squash commit message also matches the intended bump.',
    ]),
    detailsSection(commitAnalysis, titleBump),
    '',
    buildFooter(),
  ].join('\n')
}

function buildSuccessComment(title, titleBump, commitAnalysis) {
  const isRelease = titleBump !== 'none'
  const heading = isRelease ? `**Intent &middot; \`${titleBump}\` bump**` : '**Intent &middot; No Release**'

  return [
    MARKER,
    '',
    GENERATED_HEADER,
    '',
    alert(isRelease ? 'TIP' : 'NOTE', [
      heading,
      '',
      `The PR title ${code(title)} sets the intended release to a **\`${titleBump}\`** bump.`,
      '',
      `**Why:** ${BUMP_REASON[titleBump]}.`,
    ]),
    detailsSection(commitAnalysis, titleBump),
    '',
    buildFooter(),
  ].join('\n')
}

/**
 * Builds the full PR comment body from scratch. The result fully replaces any previous comment body -- no merging,
 * so there are no stale intermediate states.
 *
 * @param {{ titleResult, title, commitAnalysis, maxCommitBump }} params
 * @returns {string}
 */
function buildComment({ titleResult, title, commitAnalysis, maxCommitBump }) {
  if (!titleResult.valid) {
    return buildInvalidTitleComment(title)
  }
  const titleBump = titleResult.bumpLevel
  if (bumpGt(maxCommitBump, titleBump)) {
    return buildConflictComment(title, titleBump, maxCommitBump, commitAnalysis)
  }
  return buildSuccessComment(title, titleBump, commitAnalysis)
}

module.exports = { buildComment, buildFooter, GENERATED_FOOTER, GENERATED_HEADER, MARKER }
