'use strict'

const { bumpGt, firstLine, hasBreakingFooter } = require('./version.js')
const { bumpReason, cell, code, shortSha } = require('./render.js')

// Stable HTML-comment marker used to locate and overwrite the single bot comment.
const MARKER = '<!-- intent -->'
const GENERATED_HEADER = '### Intent Release Check'
const GENERATED_FOOTER = 'Generated by Intent'
const SQUASH_WARNING_HEADING = '### Squash merge warning'

const BUMP_REASON = {
  major: 'breaking change (`!` indicator or `BREAKING CHANGE` footer)',
  minor: '`feat` introduces new functionality',
  patch: '`fix` or `perf` corrects existing behaviour',
  none: 'no releasable change (`chore`, `docs`, `ci`, ...)',
}

function buildFooter(now = new Date()) {
  const pad = (n) => String(n).padStart(2, '0')
  const ts = `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())} ${pad(
    now.getUTCHours(),
  )}:${pad(now.getUTCMinutes())} UTC`
  return `_Last updated: ${ts} - ${GENERATED_FOOTER}_`
}

function bumpCell(bumpLevel, isConflict) {
  if (!bumpLevel || bumpLevel === 'none') return '--'
  // bumpLevel is from a fixed enum, safe to interpolate without sanitizing.
  return isConflict ? `**\`${bumpLevel}\`** :warning:` : `\`${bumpLevel}\``
}

function commitsTable(commitAnalysis, titleBump) {
  const rows = commitAnalysis.map(({ sha, message, result }) => {
    const subject = firstLine(message)
    const bump = result.bumpLevel ?? 'none'
    // A commit contributes a bump even when its subject is not valid CC -- e.g. a non-CC subject carrying a
    // BREAKING CHANGE footer. Display and conflict marking therefore key off the bump level, not the validity flag.
    const isConflict = bumpGt(bump, titleBump)
    return `| \`${shortSha(sha)}\` | ${cell(subject, 72)} | ${bumpCell(bump, isConflict)} | ${bumpReason(
      message,
      bump,
    )} |`
  })

  return ['| SHA | Subject | Bump | Reason |', '| :-- | :------ | :--: | :----- |', ...rows].join('\n')
}

function detailsSection(commitAnalysis, titleBump) {
  if (commitAnalysis.length === 0) return ''
  const n = commitAnalysis.length
  return [
    '',
    '<details>',
    `<summary>${n} commit${n === 1 ? '' : 's'} analyzed</summary>`,
    '',
    commitsTable(commitAnalysis, titleBump),
    '',
    '</details>',
  ].join('\n')
}

// -- Comment variants -------------------------------------------------------------------------------------------------

// GitHub Markdown alert. A failing check uses CAUTION (red) so it is hard to miss.
// Content lines are blockquote-prefixed; an empty string becomes a quoted blank line.
function alert(type, contentLines) {
  const body = contentLines.map((line) => (line === '' ? '>' : `> ${line}`))
  return [`> [!${type}]`, ...body].join('\n')
}

function majorNoticeLines() {
  return [
    '',
    '**Major version bump detected.**',
    'This can publish an incompatible release. Whether this is intended or accidental, confirm the breaking-change signal before merging.',
  ]
}

function maxBumpLevel(...levels) {
  return levels.reduce((max, level) => (bumpGt(level ?? 'none', max) ? level : max), 'none')
}

function releaseContextSection(releaseContext, prBump) {
  if (!releaseContext) return ''

  const defaultBranchBump = releaseContext.defaultBranchBump ?? 'none'
  const projectedBump = maxBumpLevel(defaultBranchBump, prBump)
  const lines = []

  if (defaultBranchBump !== 'none') {
    lines.push(`The default branch already requires a \`${defaultBranchBump}\` bump.`)
  }

  if (bumpGt(prBump, defaultBranchBump)) {
    lines.push(`This PR would raise the next release to \`${projectedBump}\`.`)
  }

  if (lines.length === 0) return ''
  return ['', '### Release context', '', ...lines].join('\n')
}

function squashTitleWarningSection(squashTitleWarning) {
  if (!squashTitleWarning) return ''

  return [
    '',
    SQUASH_WARNING_HEADING,
    '',
    `The PR title declares a \`${squashTitleWarning.titleBump}\` bump, but the only commit in this PR implies \`${squashTitleWarning.commitBump}\`.`,
    'With GitHub squash-merge settings that prefer the single commit title, the default-branch commit can lose the stronger PR-title signal.',
    'Before merging, make sure the final squash commit title keeps the PR title, or align the commit subject with the intended bump.',
  ].join('\n')
}

/**
 * True when an existing Intent comment reports a state that required author action (failed check or
 * squash-merge warning). Used to refresh such a comment to the resolved state once the check passes.
 */
function commentNeedsResolution(body) {
  const text = String(body ?? '')
  return text.includes('[!CAUTION]') || text.includes(SQUASH_WARNING_HEADING)
}

// -- Conflict rationale -----------------------------------------------------------------------------------------------

// One closing sentence tailored to the repository's known merge settings.
function mergeSettingsClose({ allowSquash, allowVerbatim, squashUsesPRTitle, footerConflict }) {
  if (!allowVerbatim && squashUsesPRTitle && footerConflict) {
    return (
      'This repository only allows squash merges, but a flagged `BREAKING CHANGE:` footer is copied into the ' +
      'squash commit body and will still trigger a major release. Remove the footer if the breaking change is ' +
      'not real, or update the PR title if it is.'
    )
  }
  if (!allowVerbatim && squashUsesPRTitle) {
    return (
      'This repository only allows squash merges and uses the PR title as the squash commit title, so the flagged ' +
      'commit subjects will not reach the default branch. The check still blocks because the commit record and the ' +
      'declared title contradict each other -- correct whichever side is wrong.'
    )
  }
  if (!allowVerbatim) {
    return (
      'This repository only allows squash merges, but the squash commit title is not fixed to the PR title, so a ' +
      'commit subject can still become the release signal for a single-commit merge.'
    )
  }
  if (!allowSquash) {
    return (
      'This repository does not allow squash merges: the flagged commit messages will land on the default branch ' +
      'as written.'
    )
  }
  return 'This repository allows more than one merge method, so Intent validates against the strongest interpretation.'
}

// Explains why the mismatch blocks: which of the flagged release signals reach the default branch depends on
// the merge method. Merge settings come from the event payload when the webhook serialization includes them
// (mergeSettings is null otherwise); they only tailor this guidance -- validation never depends on them.
function whyThisBlocksSection({ commitAnalysis, titleBump, mergeSettings }) {
  const conflicts = commitAnalysis.filter(({ result }) => bumpGt(result.bumpLevel ?? 'none', titleBump))
  const footerConflict = conflicts.some(({ message }) => hasBreakingFooter(message))

  const allowSquash = mergeSettings ? mergeSettings.allowSquashMerge : true
  const allowVerbatim = mergeSettings ? mergeSettings.allowMergeCommit || mergeSettings.allowRebaseMerge : true
  const squashUsesPRTitle = mergeSettings?.squashCommitTitle === 'PR_TITLE'

  const lines = [
    '',
    '### Why this blocks',
    '',
    'After merge, the release version is resolved from the commit messages that land on the default branch.',
    'Which of the flagged signals get there depends on how this PR is merged:',
    '',
  ]

  if (allowVerbatim) {
    lines.push(
      '- **Merge commit / rebase merge:** every commit lands as written, so a flagged commit message drives the release on its own.',
    )
  }
  if (allowSquash) {
    lines.push(
      '- **Squash merge** (PR title as squash commit title): commit subjects are folded into the squash commit body and lose their release effect -- only `BREAKING CHANGE:` footers are copied into the body and keep it.',
    )
  }

  lines.push('')
  if (mergeSettings) {
    lines.push(
      mergeSettingsClose({
        allowSquash,
        allowVerbatim,
        squashUsesPRTitle,
        footerConflict,
      }),
    )
  } else {
    lines.push('Intent cannot see how this PR will be merged, so it validates against the strongest interpretation.')
  }

  lines.push(
    '',
    '<details>',
    '<summary>How to rewrite a commit message</summary>',
    '',
    'Rewriting changes commit SHAs; the branch must be force-pushed afterwards. Coordinate with anyone else working on it.',
    '',
    '```bash',
    '# Reword the newest commit',
    'git commit --amend',
    '',
    '# Reword an older commit: change "pick" to "reword" for it in the editor',
    'git rebase -i <sha>^',
    '',
    '# Publish the rewritten branch',
    'git push --force-with-lease',
    '```',
    '',
    'To lower the implied bump: remove the `!` marker, use the type that matches the actual change (for example `fix:` instead of `feat:`), or delete the `BREAKING CHANGE:` footer line from the message body.',
    '',
    '</details>',
  )

  return lines.join('\n')
}

function buildInvalidTitleComment(title, releaseContext, prBump, squashTitleWarning) {
  return [
    MARKER,
    '',
    GENERATED_HEADER,
    '',
    alert('CAUTION', [
      '**Intent &middot; Invalid PR Title**',
      '',
      'Intent uses the PR title as the release signal, and this title does not follow [Conventional Commits v1.0.0](https://www.conventionalcommits.org/) format.',
      '',
      `**Got:** ${code(title || '(empty)')}`,
      '**Expected:** `<type>[scope][!]: <description>`',
      '',
      '**Allowed types:** `build`, `chore`, `ci`, `docs`, `feat`, `fix`, `perf`, `refactor`, `revert`, `style`, `test`',
      '',
      '**How to fix:** Edit the PR title in GitHub -- for example: `feat: add login` or `fix(auth)!: remove deprecated endpoint`',
    ]),
    releaseContextSection(releaseContext, prBump),
    squashTitleWarningSection(squashTitleWarning),
    '',
    buildFooter(),
  ].join('\n')
}

// Example title prefix that yields each bump level, used in the fix suggestion.
const EXAMPLE_PREFIX = { major: 'feat!', minor: 'feat', patch: 'fix' }

function buildConflictComment({
  title,
  titleBump,
  maxCommitBump,
  commitAnalysis,
  releaseContext,
  squashTitleWarning,
  mergeSettings,
}) {
  const desc = firstLine(title).replace(/^[a-z]+(\([^)]+\))?!?: /i, '') || 'description'
  const prefix = EXAMPLE_PREFIX[maxCommitBump] ?? 'feat'
  const example = code(`${prefix}: ${desc}`)

  return [
    MARKER,
    '',
    GENERATED_HEADER,
    '',
    alert('CAUTION', [
      '**Intent &middot; Release Intent Mismatch**',
      '',
      `The PR title declares a **\`${titleBump}\`** bump: ${code(title)}`,
      '',
      `One or more commits imply a higher **\`${maxCommitBump}\`** bump.`,
      ...(maxCommitBump === 'major' ? majorNoticeLines() : []),
      '',
      '**Choose the fix that matches the real intent:**',
      `- If the flagged commit message is correct, update the PR title to declare **\`${maxCommitBump}\`**, e.g. ${example}`,
      '- If it overstates the change, rewrite the flagged commit message so it no longer implies a higher bump (see the how-to below).',
    ]),
    whyThisBlocksSection({ commitAnalysis, titleBump, mergeSettings }),
    releaseContextSection(releaseContext, maxBumpLevel(titleBump, maxCommitBump)),
    squashTitleWarningSection(squashTitleWarning),
    detailsSection(commitAnalysis, titleBump),
    '',
    buildFooter(),
  ].join('\n')
}

function buildSuccessComment(title, titleBump, commitAnalysis, releaseContext, squashTitleWarning) {
  const isRelease = titleBump !== 'none'
  const isMajor = titleBump === 'major'
  const heading = isMajor
    ? '**Intent &middot; Major Version Bump**'
    : isRelease
      ? `**Intent &middot; \`${titleBump}\` bump**`
      : '**Intent &middot; No Release**'
  const alertType = isMajor ? 'WARNING' : isRelease ? 'TIP' : 'NOTE'

  return [
    MARKER,
    '',
    GENERATED_HEADER,
    '',
    alert(alertType, [
      heading,
      '',
      `The PR title ${code(title)} sets the intended release to a **\`${titleBump}\`** bump.`,
      ...(isMajor ? majorNoticeLines() : []),
      '',
      `**Why:** ${BUMP_REASON[titleBump]}.`,
    ]),
    releaseContextSection(releaseContext, titleBump),
    squashTitleWarningSection(squashTitleWarning),
    detailsSection(commitAnalysis, titleBump),
    '',
    buildFooter(),
  ].join('\n')
}

/**
 * Builds the full PR comment body from scratch. The result fully replaces any previous comment body -- no merging,
 * so there are no stale intermediate states.
 *
 * @param {{ titleResult, title, commitAnalysis, maxCommitBump, releaseContext, squashTitleWarning, mergeSettings }} params
 * @returns {string}
 */
function buildComment({
  titleResult,
  title,
  commitAnalysis,
  maxCommitBump,
  releaseContext,
  squashTitleWarning,
  mergeSettings,
}) {
  if (!titleResult.valid) {
    return buildInvalidTitleComment(title, releaseContext, maxCommitBump, squashTitleWarning)
  }
  const titleBump = titleResult.bumpLevel
  if (bumpGt(maxCommitBump, titleBump)) {
    return buildConflictComment({
      title,
      titleBump,
      maxCommitBump,
      commitAnalysis,
      releaseContext,
      squashTitleWarning,
      mergeSettings,
    })
  }
  return buildSuccessComment(title, titleBump, commitAnalysis, releaseContext, squashTitleWarning)
}

module.exports = {
  buildComment,
  buildFooter,
  commentNeedsResolution,
  GENERATED_FOOTER,
  GENERATED_HEADER,
  MARKER,
  SQUASH_WARNING_HEADING,
}
