'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const { buildComment, buildFooter, GENERATED_FOOTER, GENERATED_HEADER, MARKER } = require('./comment.js')

function makeCommit(sha, message, bumpLevel, valid = true) {
  return { sha, message, result: { valid, bumpLevel, errors: [] } }
}

// -- marker always present --------------------------------------------------------------------------------------------

test('MARKER is always present in output', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add login',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(body.includes(MARKER), 'MARKER missing from comment')
})

test('generated comment signature is always visible in output', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add login',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(body.includes(GENERATED_HEADER), 'generated header missing from comment')
  assert.ok(body.includes(GENERATED_FOOTER), 'generated footer missing from comment')
  assert.match(body, /Last updated: \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC/, 'footer timestamp missing')
})

test('generated comment signature is the final line', () => {
  const cases = [
    {
      titleResult: { valid: false, bumpLevel: null, errors: ['invalid title'] },
      title: 'WIP',
      commitAnalysis: [],
      maxCommitBump: 'none',
    },
    {
      titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
      title: 'fix: patch release',
      commitAnalysis: [makeCommit('abc1234567', 'feat!: break API', 'major')],
      maxCommitBump: 'major',
    },
    {
      titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
      title: 'feat: add login',
      commitAnalysis: [],
      maxCommitBump: 'none',
    },
  ]

  for (const params of cases) {
    assert.match(buildComment(params), /\n_Last updated: \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC - Generated by Intent_$/)
  }
})

test('buildFooter renders a stable UTC timestamp and generated signature', () => {
  const body = buildFooter(new Date(Date.UTC(2026, 0, 2, 3, 4, 5)))

  assert.equal(body, '_Last updated: 2026-01-02 03:04 UTC - Generated by Intent_')
  assert.ok(body.includes(GENERATED_FOOTER), 'generated footer sentinel missing')
})

// -- invalid title ----------------------------------------------------------------------------------------------------

test('invalid title: heading and format hint present', () => {
  const body = buildComment({
    titleResult: { valid: false, bumpLevel: null, errors: ['unknown type "wip"'] },
    title: 'WIP: do stuff',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(body.includes('[!CAUTION]'), 'caution alert missing')
  assert.ok(body.includes('Invalid PR Title'), 'heading missing')
  assert.ok(body.includes('WIP: do stuff'), 'input title missing')
  assert.ok(body.includes('How to fix'), 'fix hint missing')
})

test('invalid title: empty string handled gracefully', () => {
  const body = buildComment({
    titleResult: { valid: false, bumpLevel: null, errors: ['PR title is empty'] },
    title: '',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(body.includes('(empty)'), 'empty placeholder missing')
})

test('invalid title: aliases use the strict format hint', () => {
  const body = buildComment({
    titleResult: {
      valid: false,
      bumpLevel: null,
      errors: ['unknown type "feature"'],
    },
    title: 'feature: add login',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(body.includes('Edit the PR title in GitHub'), 'strict format hint missing')
})

// -- bump conflict ----------------------------------------------------------------------------------------------------

test('conflict: heading, both bump levels, and fix paths present', () => {
  const commits = [
    makeCommit('abc1234567', 'feat!: remove old endpoint', 'major'),
    makeCommit('def5678901', 'fix: minor correction', 'patch'),
  ]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: minor correction',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  assert.ok(body.includes('[!CAUTION]'), 'caution alert missing')
  assert.ok(body.includes('Release Intent Mismatch'), 'heading missing')
  assert.ok(body.includes('major'), 'major bump level missing')
  assert.ok(body.includes('patch'), 'title bump level missing')
  assert.ok(body.includes('If the commit message is correct'), 'title fix path missing')
  assert.ok(body.includes('overstates the change'), 'commit rewrite path missing')
  assert.ok(body.includes('squash commit message'), 'squash merge guidance missing')
})

test('conflict: conflicting commit flagged with warning in table', () => {
  const commits = [
    makeCommit('abc1234567', 'fix!: break API', 'major'),
    makeCommit('def5678901', 'chore: cleanup', 'none'),
  ]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: patch release',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  assert.ok(body.includes(':warning:'), 'warning icon missing for conflicting commit')
  assert.ok(body.includes('abc1234'), 'conflicting SHA missing')
})

test('conflict: non-conflicting commit shows dash not warning', () => {
  const commits = [makeCommit('abc1234567', 'fix!: break', 'major'), makeCommit('def5678901', 'chore: cleanup', 'none')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: release',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  // 'none' bump should show '--', not a warning
  assert.ok(body.includes('--'), 'dash missing for non-bump commit')
})

test('conflict: major mismatch calls out major release risk', () => {
  const commits = [makeCommit('abc1234567', 'feat!: break API', 'major')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add API',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  assert.ok(body.includes('Major version bump detected'), 'major notice missing')
  assert.ok(body.includes('incompatible release'), 'major risk wording missing')
})

test('conflict: release context shows default bump and PR raise', () => {
  const commits = [makeCommit('abc1234567', 'feat!: break API', 'major')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add API',
    commitAnalysis: commits,
    maxCommitBump: 'major',
    releaseContext: { defaultBranchBump: 'minor' },
  })
  assert.ok(body.includes('### Release context'), 'release context heading missing')
  assert.ok(body.includes('The default branch already requires a `minor` bump.'), 'default branch context missing')
  assert.ok(body.includes('This PR would raise the next release to `major`.'), 'PR raise context missing')
})

test('conflict: release context omits default bump line for none', () => {
  const commits = [makeCommit('abc1234567', 'feat: add API', 'minor')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: add API',
    commitAnalysis: commits,
    maxCommitBump: 'minor',
    releaseContext: { defaultBranchBump: 'none' },
  })
  assert.ok(body.includes('### Release context'), 'release context heading missing')
  assert.ok(!body.includes('The default branch already requires'), 'none default branch context should be omitted')
  assert.ok(body.includes('This PR would raise the next release to `minor`.'), 'PR raise context missing')
})

// -- success ----------------------------------------------------------------------------------------------------------

test('success: minor bump shows correct heading and reason', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add login',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(body.includes('[!TIP]'), 'tip alert missing')
  assert.ok(body.includes('minor'), 'bump level missing')
  assert.ok(body.includes('feat'), 'type reason missing')
})

test('success: none bump uses "No Release" heading', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'none', errors: [] },
    title: 'chore: update deps',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(body.includes('No Release'), 'No Release heading missing')
  assert.ok(body.includes('[!NOTE]'), 'note alert missing for no-release')
})

test('success: major bump uses warning alert and prominent wording', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'major', errors: [] },
    title: 'feat!: remove old endpoint',
    commitAnalysis: [],
    maxCommitBump: 'major',
  })
  assert.ok(body.includes('[!WARNING]'), 'major release should use warning alert')
  assert.ok(body.includes('Major Version Bump'), 'major heading missing')
  assert.ok(body.includes('Major version bump detected'), 'major notice missing')
  assert.ok(body.includes('incompatible release'), 'major risk wording missing')
})

test('success: release context shows existing default bump even when PR does not raise', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: correct bug',
    commitAnalysis: [],
    maxCommitBump: 'none',
    releaseContext: { defaultBranchBump: 'minor' },
  })
  assert.ok(body.includes('### Release context'), 'release context heading missing')
  assert.ok(body.includes('The default branch already requires a `minor` bump.'), 'default branch context missing')
  assert.ok(!body.includes('This PR would raise'), 'PR raise context should be omitted')
})

test('success: release context omits section when no line applies', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'none', errors: [] },
    title: 'chore: cleanup',
    commitAnalysis: [],
    maxCommitBump: 'none',
    releaseContext: { defaultBranchBump: 'none' },
  })
  assert.ok(!body.includes('### Release context'), 'release context should be omitted when PR does not raise')
})

test('success: squash merge warning appears when title bump exceeds the only commit bump', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'major', errors: [] },
    title: 'fix!: update storefront representation',
    commitAnalysis: [makeCommit('abc1234567', 'fix: update storefront representation', 'patch')],
    maxCommitBump: 'patch',
    squashTitleWarning: { titleBump: 'major', commitBump: 'patch' },
  })
  assert.ok(body.includes('### Squash merge warning'), 'squash warning heading missing')
  assert.ok(body.includes('PR title declares a `major` bump'), 'title bump warning missing')
  assert.ok(body.includes('only commit in this PR implies `patch`'), 'commit bump warning missing')
  assert.ok(body.includes('final squash commit title keeps the PR title'), 'squash fix guidance missing')
})

test('alert: commit table renders outside the blockquote (tables do not render inside)', () => {
  const commits = [makeCommit('abc1234567', 'feat!: break', 'major')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: release',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  // <details> must start at line beginning, never blockquote-prefixed.
  assert.ok(body.includes('\n<details>'), 'details block not at line start')
  assert.ok(!body.includes('> <details>'), 'details block wrongly inside blockquote')
})

test('success: commit table present when commits provided', () => {
  const commits = [
    makeCommit('abc1234567', 'feat: add feature', 'minor'),
    makeCommit('def5678901', 'chore: cleanup', 'none'),
  ]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add feature',
    commitAnalysis: commits,
    maxCommitBump: 'minor',
  })
  assert.ok(body.includes('<details>'), 'details section missing')
  assert.ok(body.includes('abc1234'), 'commit SHA missing')
  assert.ok(body.includes('2 commits analyzed'), 'commit count missing')
})

test('success: no details section when no commits provided', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: correct bug',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(!body.includes('<details>'), 'unexpected details section')
})

// -- commit table -----------------------------------------------------------------------------------------------------

test('non-CC commit shows dash in table', () => {
  const commits = [makeCommit('abc1234567', 'Update README', 'none', false)]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add feature',
    commitAnalysis: commits,
    maxCommitBump: 'none',
  })
  assert.ok(body.includes('--'), 'dash missing for non-CC commit')
  assert.ok(!body.includes(':warning:'), 'unexpected warning for non-CC commit')
})

test('long subject truncated to 72 chars in table', () => {
  const longSubject = `feat: ${'x'.repeat(100)}`
  const commits = [makeCommit('abc1234567', longSubject, 'minor')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add feature',
    commitAnalysis: commits,
    maxCommitBump: 'minor',
  })
  // Subject in table must be truncated (not the full 100 x's)
  assert.ok(!body.includes('x'.repeat(100)), 'subject not truncated')
  assert.ok(body.includes('...'), 'truncation indicator missing')
})

// -- Markdown sanitization --------------------------------------------------------------------------------------------

test('S01: backtick in title cannot break out of the inline-code span', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add `inline` code',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  // The raw backtick from the title must be neutralized (replaced with ').
  assert.ok(!body.includes('`feat: add `inline` code`'), 'backtick broke the span')
  assert.ok(body.includes("feat: add 'inline' code"), 'sanitized form missing')
})

test('S02: pipe in commit subject is escaped inside table cell', () => {
  const commits = [makeCommit('abc1234567', 'feat: a | b', 'minor')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add feature',
    commitAnalysis: commits,
    maxCommitBump: 'minor',
  })
  assert.ok(body.includes('feat: a \\| b'), 'pipe not escaped in table cell')
})

test('S03: @mentions and #refs in title are wrapped in code (no notifications)', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: ping @everyone closes #1',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  // Must appear only inside a backtick-wrapped span, never as bare text.
  assert.ok(body.includes('`feat: ping @everyone closes #1`'), 'mention not code-wrapped')
})

test('S04: newlines in title are collapsed to a single line', () => {
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: line one\nmalicious second line',
    commitAnalysis: [],
    maxCommitBump: 'none',
  })
  assert.ok(body.includes('`feat: line one malicious second line`'), 'newline not collapsed')
})

test('S05: bump cell enum values are never affected by sanitization', () => {
  const commits = [makeCommit('abc1234567', 'feat!: break', 'major')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: release',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  assert.ok(body.includes('**`major`** :warning:'), 'conflict bump cell missing')
})

// -- Review fix: hidden breaking footer (non-CC subject) --------------------------------------------------------------

test('F2-01: non-CC commit with breaking footer is flagged in the table', () => {
  // bumpLevel major but subject not valid CC -- must still show the bump + warning.
  const commits = [makeCommit('abc1234567', 'WIP: stuff\n\nBREAKING CHANGE: removed API', 'major', false)]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: release',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  assert.ok(body.includes('**`major`** :warning:'), 'offending commit not flagged')
  assert.ok(body.includes('abc1234'), 'offending SHA missing')
  assert.ok(body.includes('contains a `BREAKING CHANGE` footer'), 'breaking footer reason missing')
  assert.ok(!body.match(/\| `abc1234` \|[^|]*\| -- \|/), 'offending commit shown as dash')
})

// -- Review fix: fix-suggestion matches the required bump -------------------------------------------------------------

test('F3-01: patch conflict suggests fix:, not feat:', () => {
  const commits = [makeCommit('abc1234567', 'fix: small bug', 'patch')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'none', errors: [] },
    title: 'chore: cleanup',
    commitAnalysis: commits,
    maxCommitBump: 'patch',
  })
  assert.ok(body.includes('`fix: cleanup`'), 'patch suggestion should use fix:')
  assert.ok(!body.includes('`feat: cleanup`'), 'must not over-bump to feat:')
})

test('F3-02: minor conflict suggests feat:', () => {
  const commits = [makeCommit('abc1234567', 'feat: new thing', 'minor')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: correct bug',
    commitAnalysis: commits,
    maxCommitBump: 'minor',
  })
  assert.ok(body.includes('`feat: correct bug`'), 'minor suggestion should use feat:')
  assert.ok(!body.includes('feat!:'), 'must not suggest breaking')
})

test('F3-03: major conflict suggests feat!:', () => {
  const commits = [makeCommit('abc1234567', 'feat!: break', 'major')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add thing',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  assert.ok(body.includes('`feat!: add thing`'), 'major suggestion should use feat!:')
})

// -- Review fix: conflict reason explains why a commit bumps ----------------------------------------------------------

test('F4-01: feat conflict explains the minor bump reason', () => {
  const commits = [makeCommit('abc1234567', 'feat: new thing', 'minor')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'patch', errors: [] },
    title: 'fix: correct bug',
    commitAnalysis: commits,
    maxCommitBump: 'minor',
  })
  assert.ok(body.includes('`feat:` means new functionality'), 'minor bump reason missing')
  assert.ok(!body.includes('breaking-change indicator'), 'must not mention breaking indicator')
})

test('F4-02: breaking conflict explains the major bump reason', () => {
  const commits = [makeCommit('abc1234567', 'feat!: break', 'major')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add thing',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  assert.ok(body.includes('contains `!`'), 'breaking bump reason missing')
})

test('F4-03: breaking footer conflict explains the major bump reason', () => {
  const commits = [makeCommit('abc1234567', 'feat: break\n\nBREAKING CHANGE: removed API', 'major')]
  const body = buildComment({
    titleResult: { valid: true, bumpLevel: 'minor', errors: [] },
    title: 'feat: add thing',
    commitAnalysis: commits,
    maxCommitBump: 'major',
  })
  assert.ok(body.includes('contains a `BREAKING CHANGE` footer'), 'breaking footer reason missing')
})
